#! /bin/bash
# This script unloads the Linux PCIe driver from the kernel and removes the module from the system.
# You need sudo access to remove the driver.

BSP_NAME=`aocl board-name`
MODULE_NAME=aclpci_$BSP_NAME\_drv

if [[ "$MODULE_NAME" == "aclpci__drv" ]]
then
  echo Failed to determine BSP name
  exit 1
fi

MODULE_DEST=/lib/modules/`uname -r`/misc
MODPROBE_FILE_DIR=/etc/sysconfig/modules
RULE_FILE_DIR=/etc/udev/rules.d

# Unload the driver from the kernel
if [[ "`cat /proc/modules | grep "$MODULE_NAME"`" ]]; then
   sudo /sbin/modprobe -r $MODULE_NAME
fi

# Remove device from udev rules
sudo rm $RULE_FILE_DIR/99-aclpci_$BSP_NAME.rules

# Remove .modules file
sudo rm $MODPROBE_FILE_DIR/aclpci_$BSP_NAME.modules

# Remove the kernel module
sudo rm $MODULE_DEST/$MODULE_NAME.ko
